// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Theorem.Models;

namespace TheoremSlackBot.Migrations
{
    [DbContext(typeof(TheoremDbContext))]
    [Migration("20200313091111_Initial")]
    partial class Initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.2");

            modelBuilder.Entity("Theorem.Models.ChatMessageModel", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<string>("ProviderInstance")
                        .HasColumnType("TEXT");

                    b.Property<string>("ChannelId")
                        .HasColumnType("TEXT");

                    b.Property<string>("AuthorId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Body")
                        .HasColumnType("TEXT");

                    b.Property<int>("Provider")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ThreadingId")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("TimeSent")
                        .HasColumnType("TEXT");

                    b.HasKey("Id", "ProviderInstance", "ChannelId");

                    b.HasIndex("AuthorId");

                    b.HasIndex("ChannelId");

                    b.HasIndex("Id");

                    b.HasIndex("Provider");

                    b.HasIndex("ProviderInstance");

                    b.HasIndex("ThreadingId");

                    b.HasIndex("TimeSent");

                    b.ToTable("ChatMessages");
                });
#pragma warning restore 612, 618
        }
    }
}
